/**
 * Dialox Api ImamLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import {
  UpdateBussinessProfilesRequest,
  updateBussinessProfilesRequestSchema,
} from '../models/updateBussinessProfilesRequest';
import { string } from '../schema';
import { BaseController } from './baseController';

export class BusinessProfileController extends BaseController {
  /**
   * @param channelId
   * @param body
   * @return Response from the API call
   */
  async updateBussinessProfiles(
    channelId: string,
    body: UpdateBussinessProfilesRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('PATCH');
    req.baseUrl('Server 1');
    const mapped = req.prepareArgs({
      channelId: [channelId, string()],
      body: [body, updateBussinessProfilesRequestSchema],
    });
    req.json(mapped.body);
    req.appendTemplatePath`/workspaces/workspace-1/channels/${mapped.channelId}/business-profiles`;
    return req.call(requestOptions);
  }

  /**
   * @return Response from the API call
   */
  async getBusinessProfile(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest(
      'GET',
      '/workspaces/workspace-1/channels/channel-1/business-profiles'
    );
    req.baseUrl('Server 1');
    return req.call(requestOptions);
  }
}
