/**
 * Dialox Api ImamLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import {
  DocumentRequest,
  documentRequestSchema,
} from '../models/documentRequest';
import { string } from '../schema';
import { BaseController } from './baseController';

export class ExamplesController extends BaseController {
  /**
   * @param workspaceId
   * @param body
   * @return Response from the API call
   */
  async document(
    workspaceId: string,
    body: DocumentRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST');
    req.baseUrl('Server 1');
    const mapped = req.prepareArgs({
      workspaceId: [workspaceId, string()],
      body: [body, documentRequestSchema],
    });
    req.json(mapped.body);
    req.appendTemplatePath`/workspaces/${mapped.workspaceId}/conversations/9b2b3305-66f9-49cd-93eb-9d039ae94ecf/messages`;
    return req.call(requestOptions);
  }
}
