/**
 * Dialox Api ImamLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Body {
  key: string;
  valueText: string;
  value: string;
}

export const bodySchema: Schema<Body> = object({
  key: ['key', string()],
  valueText: ['value_text', string()],
  value: ['value', string()],
});
