/**
 * Dialox Api ImamLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface BroadcastBulkByFileCsvRequest {
  templateId: string;
  templateName: string;
  source: string;
  broadcastFileId: string;
  name: string;
}

export const broadcastBulkByFileCsvRequestSchema: Schema<BroadcastBulkByFileCsvRequest> = object(
  {
    templateId: ['templateId', string()],
    templateName: ['templateName', string()],
    source: ['source', string()],
    broadcastFileId: ['broadcastFileId', string()],
    name: ['name', string()],
  }
);
