/**
 * Dialox Api ImamLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string, unknown } from '../schema';

export interface BroadcastBulkByGroupRequest {
  templateId: string;
  templateName: string;
  source: string;
  groupId: string;
  name: string;
  parameters?: unknown;
}

export const broadcastBulkByGroupRequestSchema: Schema<BroadcastBulkByGroupRequest> = object(
  {
    templateId: ['templateId', string()],
    templateName: ['templateName', string()],
    source: ['source', string()],
    groupId: ['groupId', string()],
    name: ['name', string()],
    parameters: ['parameters', unknown()],
  }
);
