/**
 * Dialox Api ImamLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Button {
  index: string;
  type: string;
  value: string;
}

export const buttonSchema: Schema<Button> = object({
  index: ['index', string()],
  type: ['type', string()],
  value: ['value', string()],
});
