/**
 * Dialox Api ImamLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Button2 {
  type: string;
  text: string;
  url: string;
  urlType: string;
}

export const button2Schema: Schema<Button2> = object({
  type: ['type', string()],
  text: ['text', string()],
  url: ['url', string()],
  urlType: ['urlType', string()],
});
