/**
 * Dialox Api ImamLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, Schema } from '../schema';

export interface ChangeStatusReplyGPTRequest {
  isReplyGPT: boolean;
}

export const changeStatusReplyGPTRequestSchema: Schema<ChangeStatusReplyGPTRequest> = object(
  { isReplyGPT: ['isReplyGPT', boolean()] }
);
