/**
 * Dialox Api ImamLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface ChangeStatusConversationRequest {
  status: string;
}

export const changeStatusConversationRequestSchema: Schema<ChangeStatusConversationRequest> = object(
  { status: ['status', string()] }
);
