/**
 * Dialox Api ImamLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { Button2, button2Schema } from './button2';

export interface Component {
  type: string;
  text?: string;
  buttons?: Button2[];
}

export const componentSchema: Schema<Component> = object({
  type: ['type', string()],
  text: ['text', optional(string())],
  buttons: ['buttons', optional(array(lazy(() => button2Schema)))],
});
