/**
 * Dialox Api ImamLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Content1 {
  text: string;
}

export const content1Schema: Schema<Content1> = object({
  text: ['text', string()],
});
