/**
 * Dialox Api ImamLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Content {
  url: string;
  text: string;
  fileType: string;
}

export const contentSchema: Schema<Content> = object({
  url: ['url', string()],
  text: ['text', string()],
  fileType: ['fileType', string()],
});
