/**
 * Dialox Api ImamLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Contact {
  phoneNumber: string;
  name: string;
  email: string;
}

export const contactSchema: Schema<Contact> = object({
  phoneNumber: ['phoneNumber', string()],
  name: ['name', string()],
  email: ['email', string()],
});
