/**
 * Dialox Api ImamLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Origin, originSchema } from './origin';

export interface Conversation {
  id: string;
  expirationTimestamp: string;
  origin: Origin;
}

export const conversationSchema: Schema<Conversation> = object({
  id: ['id', string()],
  expirationTimestamp: ['expiration_timestamp', string()],
  origin: ['origin', lazy(() => originSchema)],
});
