/**
 * Dialox Api ImamLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema';
import { Component, componentSchema } from './component';

export interface CreateTemplateRequest {
  name: string;
  language: string;
  category: string;
  components: Component[];
}

export const createTemplateRequestSchema: Schema<CreateTemplateRequest> = object(
  {
    name: ['name', string()],
    language: ['language', string()],
    category: ['category', string()],
    components: ['components', array(lazy(() => componentSchema))],
  }
);
