/**
 * Dialox Api ImamLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface CreateContactRequest {
  workspaceId: string;
  name: string;
  email: string;
  phoneNumber: string;
  address: string;
}

export const createContactRequestSchema: Schema<CreateContactRequest> = object({
  workspaceId: ['workspaceId', string()],
  name: ['name', string()],
  email: ['email', string()],
  phoneNumber: ['phoneNumber', string()],
  address: ['address', string()],
});
