/**
 * Dialox Api ImamLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface CreateWorkspaceRequest {
  id: string;
  name: string;
}

export const createWorkspaceRequestSchema: Schema<CreateWorkspaceRequest> = object(
  { id: ['id', string()], name: ['name', string()] }
);
