/**
 * Dialox Api ImamLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface CreateGroupRequest {
  workspaceId: string;
  name: string;
}

export const createGroupRequestSchema: Schema<CreateGroupRequest> = object({
  workspaceId: ['workspaceId', string()],
  name: ['name', string()],
});
