/**
 * Dialox Api ImamLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Data {
  id: string;
}

export const dataSchema: Schema<Data> = object({ id: ['id', string()] });
