/**
 * Dialox Api ImamLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema';
import { Component1, component1Schema } from './component1';

export interface DeleteTemplateMessageRequest {
  name: string;
  language: string;
  category: string;
  components: Component1[];
}

export const deleteTemplateMessageRequestSchema: Schema<DeleteTemplateMessageRequest> = object(
  {
    name: ['name', string()],
    language: ['language', string()],
    category: ['category', string()],
    components: ['components', array(lazy(() => component1Schema))],
  }
);
