/**
 * Dialox Api ImamLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema';
import { Change, changeSchema } from './change';

export interface Entry {
  id: string;
  changes: Change[];
}

export const entrySchema: Schema<Entry> = object({
  id: ['id', string()],
  changes: ['changes', array(lazy(() => changeSchema))],
});
