/**
 * Dialox Api ImamLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema';
import { Param, paramSchema } from './param';

export interface Header {
  format: string;
  params: Param[];
}

export const headerSchema: Schema<Header> = object({
  format: ['format', string()],
  params: ['params', array(lazy(() => paramSchema))],
});
