/**
 * Dialox Api ImamLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Origin {
  type: string;
}

export const originSchema: Schema<Origin> = object({
  type: ['type', string()],
});
