/**
 * Dialox Api ImamLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { Body, bodySchema } from './body';

export interface Parameters {
  body: Body[];
}

export const parametersSchema: Schema<Parameters> = object({
  body: ['body', array(lazy(() => bodySchema))],
});
