/**
 * Dialox Api ImamLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, Schema, string } from '../schema';

export interface Pricing {
  billable: boolean;
  pricingModel: string;
  category: string;
}

export const pricingSchema: Schema<Pricing> = object({
  billable: ['billable', boolean()],
  pricingModel: ['pricing_model', string()],
  category: ['category', string()],
});
