/**
 * Dialox Api ImamLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface RegisterRequest {
  email: string;
  password: string;
  fullName: string;
  workspaceName: string;
  workspaceId: string;
  token: string;
}

export const registerRequestSchema: Schema<RegisterRequest> = object({
  email: ['email', string()],
  password: ['password', string()],
  fullName: ['fullName', string()],
  workspaceName: ['workspaceName', string()],
  workspaceId: ['workspaceId', string()],
  token: ['token', string()],
});
