/**
 * Dialox Api ImamLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface RequestResetPasswordRequest {
  email: string;
}

export const requestResetPasswordRequestSchema: Schema<RequestResetPasswordRequest> = object(
  { email: ['email', string()] }
);
