/**
 * Dialox Api ImamLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Data, dataSchema } from './data';

export interface Scheduler {
  data: Data;
}

export const schedulerSchema: Schema<Scheduler> = object({
  data: ['data', lazy(() => dataSchema)],
});
