/**
 * Dialox Api ImamLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string, unknown } from '../schema';

export interface SendBroadcastSingleRequest {
  broadcastName: string;
  phoneNumber: string;
  contactName: string;
  templateName: string;
  language: string;
  parameters?: unknown;
}

export const sendBroadcastSingleRequestSchema: Schema<SendBroadcastSingleRequest> = object(
  {
    broadcastName: ['broadcastName', string()],
    phoneNumber: ['phoneNumber', string()],
    contactName: ['contactName', string()],
    templateName: ['templateName', string()],
    language: ['language', string()],
    parameters: ['parameters', unknown()],
  }
);
