/**
 * Dialox Api ImamLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, object, Schema, string } from '../schema';
import { Parameters3, parameters3Schema } from './parameters3';

export interface TemplateAllRequest {
  templateId: string;
  templateName: string;
  source: string;
  groupId: string;
  name: string;
  parameters: Parameters3;
  broadcastFileId: string;
  isScheduled: boolean;
  triggerAt: string;
}

export const templateAllRequestSchema: Schema<TemplateAllRequest> = object({
  templateId: ['templateId', string()],
  templateName: ['templateName', string()],
  source: ['source', string()],
  groupId: ['groupId', string()],
  name: ['name', string()],
  parameters: ['parameters', lazy(() => parameters3Schema)],
  broadcastFileId: ['broadcastFileId', string()],
  isScheduled: ['isScheduled', boolean()],
  triggerAt: ['triggerAt', string()],
});
