/**
 * Dialox Api ImamLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Parameters2, parameters2Schema } from './parameters2';

export interface TemplateWithButtonRequest {
  broadcastName: string;
  phoneNumber: string;
  contactName: string;
  templateName: string;
  language: string;
  parameters: Parameters2;
}

export const templateWithButtonRequestSchema: Schema<TemplateWithButtonRequest> = object(
  {
    broadcastName: ['broadcastName', string()],
    phoneNumber: ['phoneNumber', string()],
    contactName: ['contactName', string()],
    templateName: ['templateName', string()],
    language: ['language', string()],
    parameters: ['parameters', lazy(() => parameters2Schema)],
  }
);
