/**
 * Dialox Api ImamLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema';
import { Contact, contactSchema } from './contact';

export interface TypeExisitngGroupRequest {
  contacts: Contact[];
  type: string;
  selectedGroup: string[];
}

export const typeExisitngGroupRequestSchema: Schema<TypeExisitngGroupRequest> = object(
  {
    contacts: ['contacts', array(lazy(() => contactSchema))],
    type: ['type', string()],
    selectedGroup: ['selectedGroup', array(string())],
  }
);
