/**
 * Dialox Api ImamLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface TypeNoneRequest {
  fileUrl: string;
  type: string;
}

export const typeNoneRequestSchema: Schema<TypeNoneRequest> = object({
  fileUrl: ['fileUrl', string()],
  type: ['type', string()],
});
