/**
 * Dialox Api ImamLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface UpdateWorkspaceByIdRequest {
  name: string;
}

export const updateWorkspaceByIdRequestSchema: Schema<UpdateWorkspaceByIdRequest> = object(
  { name: ['name', string()] }
);
