/**
 * Dialox Api ImamLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface UpdateContactRequest1 {
  workspaceId: string;
  name: string;
}

export const updateContactRequest1Schema: Schema<UpdateContactRequest1> = object(
  { workspaceId: ['workspaceId', string()], name: ['name', string()] }
);
