/**
 * Dialox Api ImamLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface VerifyResetPasswordRequest {
  token: string;
  password: string;
}

export const verifyResetPasswordRequestSchema: Schema<VerifyResetPasswordRequest> = object(
  { token: ['token', string()], password: ['password', string()] }
);
