/**
 * Dialox Api ImamLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface VerifyEmailRequest {
  token: string;
}

export const verifyEmailRequestSchema: Schema<VerifyEmailRequest> = object({
  token: ['token', string()],
});
